default_platform(:ios)

platform :mac do
  desc "j2m continuous delivery"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :release do
  increment_build_number(
    xcodeproj: "j2m.xcodeproj"
  )

  build_number = get_build_number.to_i + 1 
  
  tag = "v#{get_version_number}.#{build_number}" 
  
  analyze_commits(match: "*")
  
  gym(
    scheme: "j2m",
    export_method: "mac-application",
    destination: "platform=macOS"
  )
  
  #add_git_tag(
  #  tag: tag
  #)
  
  push_to_git_remote
  
  set_github_release(
    repository_name: "RavanSA/j2m",
    api_bearer: ENV["GITHUB_TOKEN"],
    name: "Release test",
    tag_name: tag,
    description: "test",
    commitish: "main",
    upload_assets: ["j2m.app", "j2m.app.dSYM.zip"]
  )
end
