default_platform(:ios)

platform :mac do
  desc "j2m continuous delivery"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :release do
  increment_build_number(
    xcodeproj: "j2m.xcodeproj"
  )

  build_number = get_build_number.to_i + 1 # Convert to integer and increment
  
  tag = "v#{get_version_number}.#{build_number}" # Including build number in the tag
  
  gym(
    scheme: "j2m",
    export_method: "mac-application",
    destination: "platform=macOS"
  )
  
  add_git_tag(
    tag: tag
  )
  
  push_to_git_remote
  
  notes = conventional_changelog(format: 'markdown', 
                                 title: 'test', 
                                 display_title: false, 
                                 commit_url: 'https://github.com/RavanSA/j2m/commit')
  
  set_github_release(
    repository_name: "RavanSA/j2m",
    api_bearer: ENV["GITHUB_TOKEN"],
    name: "Release #{lane_context[SharedValues::RELEASE_NEXT_VERSION]}",
    tag_name: tag,
    description: notes,
    commitish: "main",
    upload_assets: ["j2m.app", "j2m.app.dSYM.zip"]
  )
end
